// =============================================
// AAHAAR — Indian Nutrition Database
// Per 100g unless noted | Source: ICMR-NIN / USDA
// =============================================

const FOODS = [
  // ─── GRAINS & CEREALS ───────────────────────
  {
    id: "chapati",
    name: "Chapati / Roti",
    emoji: "🫓",
    category: "grains",
    serving: "1 medium (40g)",
    calories: 297,
    protein: 9.2,
    carbs: 63.7,
    fat: 1.4,
    fiber: 3.9,
    sugar: 0.5,
    vitamins: { B1: 0.38, B2: 0.17, B3: 4.3, B6: 0.3, E: 0.8 },
    minerals: { Iron: 4.6, Calcium: 34, Magnesium: 138, Phosphorus: 306, Zinc: 2.8 },
    tags: ["veg", "staple", "high-fiber"],
    description: "Whole wheat flatbread — a daily staple across India, rich in complex carbs and B vitamins.",
    healthTip: "Choose atta with bran intact. Pair with dal for a complete amino acid profile.",
    glycemicIndex: 62,
    badge: "High Fiber"
  },
  {
    id: "brown-rice",
    name: "Brown Rice (cooked)",
    emoji: "🍚",
    category: "grains",
    serving: "1 cup (195g)",
    calories: 123,
    protein: 2.7,
    carbs: 25.6,
    fat: 0.9,
    fiber: 1.8,
    sugar: 0.4,
    vitamins: { B1: 0.2, B3: 3.0, B6: 0.15, E: 0.1 },
    minerals: { Iron: 0.8, Magnesium: 84, Phosphorus: 162, Zinc: 1.2, Manganese: 1.8 },
    tags: ["veg", "staple", "whole-grain"],
    description: "Nutty, chewy brown rice retains the bran and germ layers, making it far more nutritious than white rice.",
    healthTip: "Swap white rice for brown rice — lowers glycemic load and adds magnesium.",
    glycemicIndex: 50,
    badge: "Whole Grain"
  },
  {
    id: "white-rice",
    name: "White Rice (cooked)",
    emoji: "🍚",
    category: "grains",
    serving: "1 cup (186g)",
    calories: 130,
    protein: 2.4,
    carbs: 28.2,
    fat: 0.3,
    fiber: 0.4,
    sugar: 0,
    vitamins: { B1: 0.02, B3: 1.6, B6: 0.09 },
    minerals: { Iron: 1.2, Magnesium: 19, Phosphorus: 68, Zinc: 0.5 },
    tags: ["veg", "staple"],
    description: "Polished white rice — easy to digest, low in fibre. A staple in South Indian cuisine.",
    healthTip: "Pair with sambar and rasam to compensate for lost nutrients from milling.",
    glycemicIndex: 73,
    badge: null
  },
  {
    id: "bajra-roti",
    name: "Bajra Roti (Pearl Millet)",
    emoji: "🫓",
    category: "grains",
    serving: "1 medium (40g)",
    calories: 361,
    protein: 11.6,
    carbs: 67.5,
    fat: 5.0,
    fiber: 1.2,
    sugar: 0,
    vitamins: { B1: 0.33, B2: 0.25, B3: 2.3, B6: 0.38 },
    minerals: { Iron: 8.0, Calcium: 42, Magnesium: 137, Phosphorus: 296, Zinc: 3.1 },
    tags: ["veg", "gluten-free", "iron-rich"],
    description: "Pearl millet flatbread — a Rajasthani winter staple loaded with iron and magnesium.",
    healthTip: "Great for anaemia — highest iron content among Indian flatbreads. Eat with ghee in winter.",
    glycemicIndex: 55,
    badge: "Iron Rich"
  },
  {
    id: "jowar-roti",
    name: "Jowar Roti (Sorghum)",
    emoji: "🫓",
    category: "grains",
    serving: "1 medium (40g)",
    calories: 349,
    protein: 10.4,
    carbs: 72.6,
    fat: 1.9,
    fiber: 1.6,
    sugar: 1.8,
    vitamins: { B1: 0.38, B2: 0.16, B3: 3.1 },
    minerals: { Iron: 4.1, Calcium: 25, Magnesium: 165, Phosphorus: 287, Zinc: 1.7 },
    tags: ["veg", "gluten-free"],
    description: "Sorghum flatbread popular in Maharashtra and Karnataka — gluten-free and high in antioxidants.",
    healthTip: "Excellent for people with gluten sensitivity. High magnesium supports heart health.",
    glycemicIndex: 52,
    badge: "Gluten Free"
  },
  {
    id: "poha",
    name: "Poha (Flattened Rice)",
    emoji: "🥣",
    category: "grains",
    serving: "1 plate (150g cooked)",
    calories: 76,
    protein: 1.6,
    carbs: 17.0,
    fat: 0.1,
    fiber: 0.2,
    sugar: 0,
    vitamins: { B1: 0.08, B3: 1.2, B6: 0.1 },
    minerals: { Iron: 2.0, Calcium: 5, Magnesium: 22, Phosphorus: 46 },
    tags: ["veg", "breakfast", "light"],
    description: "Flattened rice — a light, energising breakfast staple across central and western India.",
    healthTip: "Add peanuts, curry leaves and mustard seeds to poha for protein, healthy fats and antioxidants.",
    glycemicIndex: 55,
    badge: null
  },
  {
    id: "upma",
    name: "Upma (Semolina)",
    emoji: "🥣",
    category: "grains",
    serving: "1 cup (200g cooked)",
    calories: 160,
    protein: 5.0,
    carbs: 29.0,
    fat: 3.8,
    fiber: 1.5,
    sugar: 1.0,
    vitamins: { B1: 0.14, B2: 0.08, B3: 1.4 },
    minerals: { Iron: 1.5, Calcium: 14, Magnesium: 35, Phosphorus: 78 },
    tags: ["veg", "breakfast"],
    description: "Semolina porridge tempered with mustard, curry leaves, and vegetables — South Indian breakfast classic.",
    healthTip: "Add extra vegetables like carrots and peas to boost vitamins and fibre.",
    glycemicIndex: 66,
    badge: null
  },
  {
    id: "idli",
    name: "Idli",
    emoji: "🍘",
    category: "grains",
    serving: "2 medium idlis (100g)",
    calories: 58,
    protein: 2.0,
    carbs: 11.4,
    fat: 0.2,
    fiber: 0.5,
    sugar: 0,
    vitamins: { B1: 0.1, B2: 0.07, B12: 0.1 },
    minerals: { Iron: 0.6, Calcium: 8, Magnesium: 14, Phosphorus: 40 },
    tags: ["veg", "fermented", "low-calorie", "probiotic"],
    description: "Fermented rice-lentil steamed cake — naturally probiotic, low-fat, and extremely gentle on the gut.",
    healthTip: "Fermentation increases B12 and improves mineral absorption. Pair with sambar for complete nutrition.",
    glycemicIndex: 35,
    badge: "Probiotic"
  },
  {
    id: "dosa",
    name: "Dosa (Plain)",
    emoji: "🥞",
    category: "grains",
    serving: "1 large dosa (90g)",
    calories: 133,
    protein: 3.4,
    carbs: 25.3,
    fat: 2.7,
    fiber: 0.9,
    sugar: 0.5,
    vitamins: { B1: 0.06, B2: 0.07, B3: 0.8 },
    minerals: { Iron: 0.8, Calcium: 14, Magnesium: 27, Phosphorus: 60 },
    tags: ["veg", "fermented", "probiotic"],
    description: "Thin crispy fermented crepe from South India — beloved at every breakfast table.",
    healthTip: "Opt for masala dosa with potato-onion filling to add potassium. Use minimal oil.",
    glycemicIndex: 69,
    badge: null
  },
  {
    id: "quinoa",
    name: "Quinoa (cooked)",
    emoji: "🌾",
    category: "grains",
    serving: "1 cup (185g)",
    calories: 222,
    protein: 8.1,
    carbs: 39.4,
    fat: 3.6,
    fiber: 5.2,
    sugar: 1.6,
    vitamins: { B1: 0.2, B2: 0.2, B6: 0.2, E: 1.2, Folate: 78 },
    minerals: { Iron: 2.8, Calcium: 31, Magnesium: 118, Phosphorus: 281, Zinc: 2.0 },
    tags: ["veg", "gluten-free", "complete-protein", "high-fiber"],
    description: "Technically a seed but used as grain — one of the few complete plant proteins, rich in all 9 essential amino acids.",
    healthTip: "Rinse thoroughly to remove saponins. Use as a base for salads or instead of rice.",
    glycemicIndex: 53,
    badge: "Complete Protein"
  },

  // ─── DAL & LEGUMES ───────────────────────────
  {
    id: "moong-dal",
    name: "Moong Dal (Yellow, cooked)",
    emoji: "🟡",
    category: "lentils",
    serving: "1 cup (195g cooked)",
    calories: 105,
    protein: 7.0,
    carbs: 19.0,
    fat: 0.4,
    fiber: 7.6,
    sugar: 2.0,
    vitamins: { B1: 0.22, B2: 0.07, B3: 1.5, Folate: 159, C: 1.6 },
    minerals: { Iron: 1.4, Calcium: 27, Magnesium: 48, Phosphorus: 149, Zinc: 1.0, Potassium: 369 },
    tags: ["veg", "high-protein", "high-fiber", "easy-digest"],
    description: "Yellow split mung — lightest of all Indian dals, easy on digestion, high in folate and potassium.",
    healthTip: "Perfect for sick days and post-illness recovery. Khichdi with moong dal is India's original comfort food.",
    glycemicIndex: 25,
    badge: "Easy Digest"
  },
  {
    id: "masoor-dal",
    name: "Masoor Dal (Red Lentil)",
    emoji: "🔴",
    category: "lentils",
    serving: "1 cup (198g cooked)",
    calories: 116,
    protein: 9.0,
    carbs: 20.1,
    fat: 0.4,
    fiber: 7.8,
    sugar: 1.8,
    vitamins: { B1: 0.17, B3: 1.1, Folate: 179, B6: 0.18 },
    minerals: { Iron: 3.3, Calcium: 19, Magnesium: 36, Phosphorus: 178, Zinc: 1.3, Potassium: 369 },
    tags: ["veg", "high-protein", "iron-rich"],
    description: "Red lentil — cooks quickly, high in iron and folate. A protein powerhouse for vegetarians.",
    healthTip: "Squeeze lemon over dal tadka — vitamin C dramatically boosts iron absorption from plant sources.",
    glycemicIndex: 21,
    badge: "Iron Rich"
  },
  {
    id: "chana-dal",
    name: "Chana Dal (Split Chickpea)",
    emoji: "🟤",
    category: "lentils",
    serving: "1 cup (200g cooked)",
    calories: 164,
    protein: 8.9,
    carbs: 29.0,
    fat: 2.7,
    fiber: 7.9,
    sugar: 5.6,
    vitamins: { B1: 0.2, B6: 0.35, Folate: 141, B3: 1.2 },
    minerals: { Iron: 2.5, Calcium: 49, Magnesium: 45, Phosphorus: 168, Zinc: 1.3, Potassium: 296 },
    tags: ["veg", "high-protein", "high-fiber"],
    description: "Bengal gram dal — nutty flavour, slower digestion, and excellent for blood sugar management.",
    healthTip: "Among the lowest glycemic index legumes. Ideal for diabetics as part of a balanced meal.",
    glycemicIndex: 8,
    badge: "Low GI"
  },
  {
    id: "rajma",
    name: "Rajma (Kidney Beans, cooked)",
    emoji: "🫘",
    category: "lentils",
    serving: "1 cup (177g cooked)",
    calories: 225,
    protein: 15.3,
    carbs: 40.4,
    fat: 0.9,
    fiber: 11.3,
    sugar: 0.6,
    vitamins: { B1: 0.28, B6: 0.28, Folate: 230, B3: 2.1 },
    minerals: { Iron: 5.2, Calcium: 62, Magnesium: 74, Phosphorus: 244, Zinc: 1.8, Potassium: 715 },
    tags: ["veg", "high-protein", "high-fiber", "iron-rich"],
    description: "Kidney beans — the pride of Punjabi cooking. Extraordinarily high in iron, folate, and potassium.",
    healthTip: "Rajma-chawal is one of the most nutritionally complete Indian meals. Always soak overnight before cooking.",
    glycemicIndex: 24,
    badge: "Protein Powerhouse"
  },
  {
    id: "chole",
    name: "Chole (Chickpeas, cooked)",
    emoji: "🫘",
    category: "lentils",
    serving: "1 cup (164g cooked)",
    calories: 269,
    protein: 14.5,
    carbs: 45.0,
    fat: 4.3,
    fiber: 12.5,
    sugar: 7.9,
    vitamins: { B1: 0.19, B6: 0.23, Folate: 282, B3: 0.86 },
    minerals: { Iron: 4.7, Calcium: 80, Magnesium: 78, Phosphorus: 276, Zinc: 2.5, Potassium: 477 },
    tags: ["veg", "high-protein", "high-fiber"],
    description: "Chickpeas — versatile, hearty, and among the most nutrient-dense legumes in Indian cuisine.",
    healthTip: "Excellent satiety food — high protein + fibre combination keeps you full for hours.",
    glycemicIndex: 28,
    badge: "High Satiety"
  },
  {
    id: "urad-dal",
    name: "Urad Dal (Black Gram)",
    emoji: "⚫",
    category: "lentils",
    serving: "1 cup (180g cooked)",
    calories: 207,
    protein: 14.0,
    carbs: 36.5,
    fat: 1.1,
    fiber: 5.5,
    sugar: 0,
    vitamins: { B1: 0.28, B2: 0.14, B3: 1.5, Folate: 242 },
    minerals: { Iron: 3.4, Calcium: 138, Magnesium: 149, Phosphorus: 302, Zinc: 1.9, Potassium: 983 },
    tags: ["veg", "high-protein", "calcium-rich"],
    description: "Black gram — base for dal makhani and idli batter. Exceptional calcium and potassium content.",
    healthTip: "Dal makhani: slow cook overnight for deeper flavour and better digestibility.",
    glycemicIndex: 43,
    badge: "Calcium Rich"
  },
  {
    id: "moth-beans",
    name: "Moth Beans (sprouted)",
    emoji: "🌱",
    category: "lentils",
    serving: "1 cup (100g)",
    calories: 343,
    protein: 22.9,
    carbs: 62.4,
    fat: 1.6,
    fiber: 4.5,
    sugar: 0,
    vitamins: { B1: 0.35, B2: 0.17, B3: 2.1, C: 11.8, Folate: 200 },
    minerals: { Iron: 7.8, Calcium: 202, Magnesium: 190, Phosphorus: 408, Zinc: 2.7 },
    tags: ["veg", "sprouted", "high-protein", "iron-rich"],
    description: "Moth beans — sprouting dramatically increases vitamin C and makes nutrients more bioavailable.",
    healthTip: "Sprouting increases nutrient absorption by up to 50%. Add raw to salads for maximum benefit.",
    glycemicIndex: 30,
    badge: "Sprouted Power"
  },

  // ─── VEGETABLES ──────────────────────────────
  {
    id: "spinach",
    name: "Palak (Spinach)",
    emoji: "🥬",
    category: "vegetables",
    serving: "1 cup (30g raw)",
    calories: 23,
    protein: 2.9,
    carbs: 3.6,
    fat: 0.4,
    fiber: 2.2,
    sugar: 0.4,
    vitamins: { A: 469, C: 28.1, K: 483, Folate: 194, B2: 0.19, E: 2.0 },
    minerals: { Iron: 2.7, Calcium: 99, Magnesium: 79, Phosphorus: 49, Potassium: 558 },
    tags: ["veg", "leafy", "iron-rich", "low-calorie"],
    description: "Palak — India's iron queen. Astounding vitamin K and A content alongside iron.",
    healthTip: "Cook with a small amount of fat to absorb fat-soluble vitamins A and K. Pair with lemon for iron uptake.",
    glycemicIndex: 15,
    badge: "Superfood"
  },
  {
    id: "fenugreek",
    name: "Methi (Fenugreek Leaves)",
    emoji: "🌿",
    category: "vegetables",
    serving: "1 cup (149g cooked)",
    calories: 36,
    protein: 2.5,
    carbs: 6.0,
    fat: 0.7,
    fiber: 3.9,
    sugar: 0.6,
    vitamins: { A: 33, C: 3.0, K: 620, Folate: 57, B2: 0.13 },
    minerals: { Iron: 3.7, Calcium: 176, Magnesium: 21, Phosphorus: 33, Potassium: 189 },
    tags: ["veg", "leafy", "diabetic-friendly", "iron-rich"],
    description: "Methi — bitter, powerful, and medicinal. Unique fenugreekine compound helps regulate blood sugar.",
    healthTip: "Soak methi seeds overnight in water — a tablespoon in morning helps manage type 2 diabetes.",
    glycemicIndex: 25,
    badge: "Blood Sugar"
  },
  {
    id: "drumstick",
    name: "Drumstick (Moringa)",
    emoji: "🌿",
    category: "vegetables",
    serving: "100g",
    calories: 37,
    protein: 2.1,
    carbs: 8.5,
    fat: 0.2,
    fiber: 3.2,
    sugar: 3.2,
    vitamins: { A: 84, C: 141, B1: 0.05, B2: 0.07, B3: 0.62 },
    minerals: { Iron: 0.36, Calcium: 25, Magnesium: 45, Phosphorus: 50, Potassium: 461 },
    tags: ["veg", "vitamin-c", "antioxidant"],
    description: "Moringa pods (murungakkai / sahjan) — used in sambar across South India, extraordinarily rich in vitamin C.",
    healthTip: "Moringa leaves (powder) contain 7× more vitamin C than oranges and 4× more calcium than milk.",
    glycemicIndex: 20,
    badge: "Vitamin C"
  },
  {
    id: "bitter-gourd",
    name: "Karela (Bitter Gourd)",
    emoji: "🥒",
    category: "vegetables",
    serving: "100g",
    calories: 17,
    protein: 1.0,
    carbs: 3.7,
    fat: 0.17,
    fiber: 2.8,
    sugar: 1.7,
    vitamins: { C: 84, A: 24, K: 4.8, B1: 0.04, Folate: 72 },
    minerals: { Iron: 0.4, Calcium: 19, Magnesium: 17, Phosphorus: 31, Potassium: 296, Zinc: 0.8 },
    tags: ["veg", "diabetic-friendly", "low-calorie"],
    description: "Karela — bitter medicine in vegetable form. Charantin and momordicin lower blood glucose.",
    healthTip: "Juice of karela + amla in the morning is one of Ayurveda's most potent diabetes remedies.",
    glycemicIndex: 10,
    badge: "Diabetic Friendly"
  },
  {
    id: "bottle-gourd",
    name: "Lauki (Bottle Gourd)",
    emoji: "🥒",
    category: "vegetables",
    serving: "100g",
    calories: 14,
    protein: 0.6,
    carbs: 3.4,
    fat: 0,
    fiber: 0.5,
    sugar: 2.5,
    vitamins: { C: 10, B1: 0.02, B2: 0.02, B3: 0.4 },
    minerals: { Iron: 0.5, Calcium: 26, Magnesium: 11, Phosphorus: 13, Potassium: 170 },
    tags: ["veg", "weight-loss", "low-calorie", "hydrating"],
    description: "Lauki — 96% water, extremely low calorie. Used in Indian weight loss diets since ancient times.",
    healthTip: "Lauki juice in summer keeps you hydrated and aids kidney function. Avoid if raw juice tastes bitter.",
    glycemicIndex: 15,
    badge: "Weight Loss"
  },
  {
    id: "sweet-potato",
    name: "Shakarkandi (Sweet Potato)",
    emoji: "🍠",
    category: "vegetables",
    serving: "1 medium (130g)",
    calories: 103,
    protein: 2.3,
    carbs: 24.0,
    fat: 0.1,
    fiber: 3.8,
    sugar: 7.4,
    vitamins: { A: 1096, C: 22.3, B6: 0.33, B5: 0.95, E: 0.26 },
    minerals: { Iron: 0.7, Calcium: 39, Magnesium: 27, Phosphorus: 54, Potassium: 438 },
    tags: ["veg", "vitamin-a", "high-fiber", "antioxidant"],
    description: "Sweet potato — one of the richest plant sources of beta-carotene (vitamin A precursor).",
    healthTip: "Eat with skin for maximum fibre. Baking preserves more nutrients than boiling.",
    glycemicIndex: 61,
    badge: "Vitamin A"
  },
  {
    id: "pumpkin",
    name: "Kaddu (Pumpkin)",
    emoji: "🎃",
    category: "vegetables",
    serving: "100g",
    calories: 26,
    protein: 1.0,
    carbs: 6.5,
    fat: 0.1,
    fiber: 0.5,
    sugar: 2.8,
    vitamins: { A: 426, C: 9.0, E: 1.06, K: 1.1, B6: 0.06 },
    minerals: { Iron: 0.8, Calcium: 21, Magnesium: 12, Phosphorus: 44, Potassium: 340 },
    tags: ["veg", "low-calorie", "vitamin-a"],
    description: "Kaddu — deep orange colour signals enormous beta-carotene. Cooked with spices across Indian regions.",
    healthTip: "Pumpkin seeds (magaj) are nutritional gems — rich in zinc, magnesium and healthy fats. Don't discard them.",
    glycemicIndex: 75,
    badge: null
  },
  {
    id: "tomato",
    name: "Tamatar (Tomato)",
    emoji: "🍅",
    category: "vegetables",
    serving: "1 medium (123g)",
    calories: 22,
    protein: 1.1,
    carbs: 4.8,
    fat: 0.2,
    fiber: 1.5,
    sugar: 3.2,
    vitamins: { C: 23.4, A: 75, K: 9.7, B6: 0.09, E: 0.54, Folate: 18 },
    minerals: { Iron: 0.5, Calcium: 18, Magnesium: 20, Phosphorus: 43, Potassium: 427 },
    tags: ["veg", "antioxidant", "low-calorie"],
    description: "Tomato — base of half of Indian cooking. Lycopene (powerful antioxidant) increases when cooked.",
    healthTip: "Cooking tomatoes in a little oil increases lycopene bioavailability by 300%. Use for tadka, not just salads.",
    glycemicIndex: 15,
    badge: "Lycopene"
  },

  // ─── DAIRY ───────────────────────────────────
  {
    id: "paneer",
    name: "Paneer (Indian Cottage Cheese)",
    emoji: "🧀",
    category: "dairy",
    serving: "100g",
    calories: 265,
    protein: 18.3,
    carbs: 1.2,
    fat: 20.8,
    fiber: 0,
    sugar: 1.2,
    vitamins: { A: 262, B2: 0.25, B12: 0.5, D: 3.5 },
    minerals: { Calcium: 476, Phosphorus: 345, Iron: 0.3, Magnesium: 8, Zinc: 2.2 },
    tags: ["veg", "high-protein", "calcium-rich", "keto-friendly"],
    description: "Paneer — the vegetarian's meat. Slow-digesting casein protein and supreme calcium make it unmissable.",
    healthTip: "Make at home with full-fat milk and lemon juice. Homemade paneer has no preservatives.",
    glycemicIndex: 27,
    badge: "Calcium Rich"
  },
  {
    id: "curd",
    name: "Dahi (Curd / Yogurt)",
    emoji: "🥛",
    category: "dairy",
    serving: "1 cup (245g)",
    calories: 149,
    protein: 8.5,
    carbs: 11.4,
    fat: 8.0,
    fiber: 0,
    sugar: 11.4,
    vitamins: { B12: 1.0, B2: 0.34, A: 243, D: 2.0 },
    minerals: { Calcium: 296, Phosphorus: 233, Potassium: 380, Zinc: 1.5, Magnesium: 27 },
    tags: ["veg", "probiotic", "calcium-rich", "gut-health"],
    description: "Dahi — India's original probiotic. Live cultures support gut microbiome, immunity and digestion.",
    healthTip: "Eat curd at room temperature, not cold. Adding jeera and black salt enhances digestive properties.",
    glycemicIndex: 36,
    badge: "Probiotic"
  },
  {
    id: "lassi",
    name: "Lassi (Sweet)",
    emoji: "🥛",
    category: "dairy",
    serving: "1 glass (300ml)",
    calories: 149,
    protein: 6.0,
    carbs: 22.0,
    fat: 4.5,
    fiber: 0,
    sugar: 22.0,
    vitamins: { B12: 0.8, B2: 0.25, A: 165 },
    minerals: { Calcium: 218, Phosphorus: 171, Potassium: 350, Zinc: 1.0 },
    tags: ["veg", "probiotic", "summer-drink"],
    description: "Chilled blended yogurt drink — Punjab's answer to summer hydration. Refreshing and protein-rich.",
    healthTip: "Choose salted/namkeen lassi over sweet lassi to avoid excess sugar while still getting probiotics.",
    glycemicIndex: 45,
    badge: null
  },
  {
    id: "ghee",
    name: "Ghee (Clarified Butter)",
    emoji: "🧈",
    category: "dairy",
    serving: "1 tsp (5g)",
    calories: 45,
    protein: 0.04,
    carbs: 0,
    fat: 5.0,
    fiber: 0,
    sugar: 0,
    vitamins: { A: 438, E: 2.8, K: 1.0, D: 15 },
    minerals: { Calcium: 1, Phosphorus: 1 },
    tags: ["veg", "fat", "ayurvedic"],
    description: "Pure clarified butter — concentrated fat with fat-soluble vitamins. Revered in Ayurveda as a healing food.",
    healthTip: "1 tsp per meal is health-promoting. Contains butyrate which feeds gut lining cells. Don't fear it — avoid excess.",
    glycemicIndex: 0,
    badge: "Ayurvedic"
  },
  {
    id: "milk",
    name: "Full-fat Milk",
    emoji: "🥛",
    category: "dairy",
    serving: "1 glass (240ml)",
    calories: 149,
    protein: 8.0,
    carbs: 11.7,
    fat: 8.0,
    fiber: 0,
    sugar: 11.7,
    vitamins: { B12: 1.1, B2: 0.35, A: 307, D: 2.9, B5: 0.9 },
    minerals: { Calcium: 276, Phosphorus: 205, Potassium: 349, Zinc: 1.0, Magnesium: 24 },
    tags: ["veg", "calcium-rich", "protein"],
    description: "Whole cow's milk — complete nutrition, the most bioavailable calcium source for growing Indians.",
    healthTip: "Warm milk before sleep with haldi (turmeric) — reduces inflammation, aids sleep, and delivers tryptophan.",
    glycemicIndex: 32,
    badge: "Complete Nutrition"
  },

  // ─── SNACKS & STREET FOOD ────────────────────
  {
    id: "samosa",
    name: "Samosa (Potato)",
    emoji: "🥟",
    category: "snacks",
    serving: "1 piece (60g)",
    calories: 262,
    protein: 3.5,
    carbs: 27.0,
    fat: 15.8,
    fiber: 1.8,
    sugar: 2.0,
    vitamins: { C: 3.8, B1: 0.1, B3: 0.9 },
    minerals: { Iron: 1.1, Calcium: 18, Phosphorus: 55, Potassium: 280 },
    tags: ["veg", "fried", "indulgence"],
    description: "Crispy fried pastry filled with spiced potato — the quintessential Indian snack.",
    healthTip: "Bake samosas at 200°C for 25 min instead of frying to cut fat content by nearly 60%.",
    glycemicIndex: 55,
    badge: null
  },
  {
    id: "pakora",
    name: "Pakoda / Bhajiya",
    emoji: "🍘",
    category: "snacks",
    serving: "4 pieces (60g)",
    calories: 160,
    protein: 3.9,
    carbs: 16.6,
    fat: 9.0,
    fiber: 1.5,
    sugar: 0.8,
    vitamins: { C: 2.0, B1: 0.07, B3: 0.6 },
    minerals: { Iron: 1.0, Calcium: 33, Phosphorus: 65, Potassium: 135 },
    tags: ["veg", "fried", "monsoon"],
    description: "Gram-flour battered and fried vegetables — best enjoyed with chai on monsoon evenings.",
    healthTip: "Air-fry or oven-bake pakodas. Besan (chickpea flour) itself is nutritious — the frying undoes it.",
    glycemicIndex: 52,
    badge: null
  },
  {
    id: "peanuts",
    name: "Moongphali (Roasted Peanuts)",
    emoji: "🥜",
    category: "snacks",
    serving: "1 small handful (30g)",
    calories: 171,
    protein: 7.8,
    carbs: 6.2,
    fat: 14.6,
    fiber: 2.4,
    sugar: 1.1,
    vitamins: { B3: 3.8, E: 2.3, B1: 0.15, B6: 0.1, Folate: 68 },
    minerals: { Iron: 1.3, Magnesium: 52, Phosphorus: 107, Zinc: 0.93, Potassium: 200 },
    tags: ["veg", "high-protein", "healthy-fat", "snack"],
    description: "Roasted peanuts — the most affordable protein-rich snack in India, high in niacin and monounsaturated fats.",
    healthTip: "A daily handful reduces heart disease risk. Choose unsalted, dry-roasted over oil-fried varieties.",
    glycemicIndex: 14,
    badge: "Heart Healthy"
  },
  {
    id: "chaat",
    name: "Pani Puri / Golgappa",
    emoji: "🍡",
    category: "snacks",
    serving: "6 pieces (120g)",
    calories: 180,
    protein: 3.5,
    carbs: 34.0,
    fat: 4.0,
    fiber: 2.5,
    sugar: 4.0,
    vitamins: { C: 4.5, B1: 0.08, B3: 0.8 },
    minerals: { Iron: 1.5, Calcium: 25, Phosphorus: 60, Potassium: 180 },
    tags: ["veg", "street-food", "snack"],
    description: "Crispy semolina shells filled with tangy tamarind water — India's most beloved street snack.",
    healthTip: "Ask for extra jeera water and mint. Avoid roadside versions during monsoon — hygiene risks are high.",
    glycemicIndex: 60,
    badge: null
  },

  // ─── SWEETS ──────────────────────────────────
  {
    id: "halwa",
    name: "Gajar Halwa (Carrot Pudding)",
    emoji: "🟠",
    category: "sweets",
    serving: "1 cup (100g)",
    calories: 254,
    protein: 4.0,
    carbs: 35.0,
    fat: 11.5,
    fiber: 2.7,
    sugar: 28.0,
    vitamins: { A: 1243, B12: 0.2, D: 1.0, B2: 0.12 },
    minerals: { Calcium: 124, Phosphorus: 109, Iron: 0.6, Potassium: 340 },
    tags: ["veg", "sweet", "vitamin-a"],
    description: "Slow-cooked carrot dessert in ghee and milk — a winter treat hiding extraordinary beta-carotene.",
    healthTip: "Use jaggery instead of sugar and low-fat milk to get vitamin A goodness with less sugar spike.",
    glycemicIndex: 55,
    badge: null
  },
  {
    id: "jaggery",
    name: "Gur / Jaggery",
    emoji: "🟫",
    category: "sweets",
    serving: "1 tsp (5g)",
    calories: 19,
    protein: 0.01,
    carbs: 4.9,
    fat: 0,
    fiber: 0,
    sugar: 4.6,
    vitamins: { B1: 0.01, B3: 0.2 },
    minerals: { Iron: 0.6, Calcium: 8, Magnesium: 7, Phosphorus: 4, Potassium: 14 },
    tags: ["veg", "natural-sweetener", "iron"],
    description: "Unrefined cane sugar — retains minerals stripped away from white sugar. Traditional post-meal digestive.",
    healthTip: "Replace white sugar with jaggery for small iron and mineral benefit. Still a sugar — use in moderation.",
    glycemicIndex: 84,
    badge: "Natural Sweetener"
  },
  {
    id: "kheer",
    name: "Rice Kheer",
    emoji: "🍮",
    category: "sweets",
    serving: "1 cup (200g)",
    calories: 204,
    protein: 5.6,
    carbs: 33.0,
    fat: 6.0,
    fiber: 0.3,
    sugar: 22.0,
    vitamins: { B12: 0.5, B2: 0.2, A: 140, D: 1.0 },
    minerals: { Calcium: 166, Phosphorus: 132, Potassium: 230, Magnesium: 18 },
    tags: ["veg", "sweet", "calcium-rich"],
    description: "Creamy rice pudding with milk, sugar and cardamom — festive, comforting, and calcium-rich.",
    healthTip: "Make with brown rice and reduce sugar by 30%. Add saffron and almonds for extra antioxidants.",
    glycemicIndex: 68,
    badge: null
  },

  // ─── BEVERAGES ────────────────────────────────
  {
    id: "masala-chai",
    name: "Masala Chai (with milk)",
    emoji: "☕",
    category: "beverages",
    serving: "1 cup (240ml)",
    calories: 120,
    protein: 3.0,
    carbs: 18.0,
    fat: 4.0,
    fiber: 0.4,
    sugar: 14.0,
    vitamins: { B12: 0.4, B2: 0.15, A: 140 },
    minerals: { Calcium: 110, Phosphorus: 90, Potassium: 215, Magnesium: 12 },
    tags: ["beverage", "antioxidant", "warm"],
    description: "Spiced black tea with milk — ginger, cardamom, cinnamon and cloves add powerful antioxidants.",
    healthTip: "Reduce sugar to ½ tsp per cup. Ginger aids digestion, cardamom freshens breath, cinnamon controls blood sugar.",
    glycemicIndex: 55,
    badge: "Antioxidant"
  },
  {
    id: "amla-juice",
    name: "Amla Juice (Indian Gooseberry)",
    emoji: "🟢",
    category: "beverages",
    serving: "100ml",
    calories: 44,
    protein: 0.9,
    carbs: 10.2,
    fat: 0.6,
    fiber: 4.3,
    sugar: 6.9,
    vitamins: { C: 600, A: 17, E: 0.37, Folate: 6 },
    minerals: { Iron: 0.31, Calcium: 25, Phosphorus: 27, Potassium: 198 },
    tags: ["beverage", "vitamin-c", "antioxidant", "immunity"],
    description: "Indian gooseberry juice — one of the world's most concentrated vitamin C sources. 20× more than orange.",
    healthTip: "30ml amla juice each morning on empty stomach enhances immunity, hair growth, and skin collagen.",
    glycemicIndex: 15,
    badge: "Vitamin C King"
  },
  {
    id: "coconut-water",
    name: "Coconut Water (Nariyal Pani)",
    emoji: "🥥",
    category: "beverages",
    serving: "1 tender coconut (240ml)",
    calories: 46,
    protein: 1.7,
    carbs: 8.9,
    fat: 0.5,
    fiber: 2.6,
    sugar: 6.0,
    vitamins: { C: 5.8, B2: 0.14, B3: 0.08, Folate: 16 },
    minerals: { Potassium: 600, Calcium: 58, Magnesium: 60, Phosphorus: 48, Sodium: 252 },
    tags: ["beverage", "electrolyte", "hydrating", "summer"],
    description: "Natural isotonic drink — potassium and electrolyte content rivals commercial sports drinks.",
    healthTip: "Best natural ORS (oral rehydration solution). Drink after workouts or during fever for electrolyte replenishment.",
    glycemicIndex: 54,
    badge: "Natural Electrolyte"
  },
  {
    id: "haldi-milk",
    name: "Haldi Doodh (Golden Milk)",
    emoji: "🟡",
    category: "beverages",
    serving: "1 cup (240ml)",
    calories: 140,
    protein: 7.5,
    carbs: 12.5,
    fat: 6.5,
    fiber: 0.2,
    sugar: 10.5,
    vitamins: { A: 250, D: 2.5, B12: 0.9, B2: 0.3 },
    minerals: { Calcium: 260, Phosphorus: 195, Potassium: 380, Iron: 1.2, Manganese: 0.8 },
    tags: ["beverage", "anti-inflammatory", "immunity", "bedtime"],
    description: "Warm milk infused with turmeric — curcumin + fat-soluble base = maximum anti-inflammatory absorption.",
    healthTip: "Add a pinch of black pepper (piperine) — increases curcumin absorption by 2000%. A must before bedtime.",
    glycemicIndex: 32,
    badge: "Anti-Inflammatory"
  },

  // ─── NON-VEG ─────────────────────────────────
  {
    id: "chicken-curry",
    name: "Chicken Curry (home-style)",
    emoji: "🍗",
    category: "nonveg",
    serving: "1 serving (200g)",
    calories: 240,
    protein: 25.0,
    carbs: 8.5,
    fat: 12.0,
    fiber: 1.0,
    sugar: 3.5,
    vitamins: { B3: 8.9, B6: 0.9, B12: 0.3, A: 60, D: 0.2 },
    minerals: { Iron: 1.5, Phosphorus: 220, Potassium: 380, Zinc: 2.0, Selenium: 22 },
    tags: ["non-veg", "high-protein", "lean-meat"],
    description: "Slow-cooked chicken with onion, tomato and spices — the most complete protein on a typical Indian plate.",
    healthTip: "Skin-off chicken breast is leanest. The spices (haldi, jeera, dhaniya) add antioxidants at zero calories.",
    glycemicIndex: 0,
    badge: "High Protein"
  },
  {
    id: "egg",
    name: "Anda (Whole Egg, boiled)",
    emoji: "🥚",
    category: "nonveg",
    serving: "1 large egg (50g)",
    calories: 78,
    protein: 6.3,
    carbs: 0.6,
    fat: 5.3,
    fiber: 0,
    sugar: 0.6,
    vitamins: { B12: 0.6, A: 270, D: 44, B2: 0.26, B5: 0.7, Folate: 24 },
    minerals: { Iron: 1.0, Phosphorus: 99, Selenium: 15.4, Zinc: 0.6, Calcium: 28 },
    tags: ["non-veg", "complete-protein", "vitamin-d"],
    description: "Whole egg — the gold standard of protein quality. The yolk holds nearly all the vitamins and minerals.",
    healthTip: "Don't discard the yolk — it has vitamin D, choline and lutein. For most people, 1-2 eggs daily is fine.",
    glycemicIndex: 0,
    badge: "Nature's Multivitamin"
  },
  {
    id: "fish-curry",
    name: "Machli Curry (Fish Curry)",
    emoji: "🐟",
    category: "nonveg",
    serving: "1 serving (180g)",
    calories: 210,
    protein: 22.0,
    carbs: 6.5,
    fat: 10.5,
    fiber: 0.8,
    sugar: 2.0,
    vitamins: { B12: 2.5, D: 11.0, B3: 7.0, A: 55, E: 1.5 },
    minerals: { Omega3: 1.8, Phosphorus: 310, Selenium: 36, Potassium: 420, Calcium: 28, Iron: 1.2 },
    tags: ["non-veg", "omega-3", "vitamin-d", "heart-healthy"],
    description: "Spiced fish curry — excellent source of omega-3 fatty acids and vitamin D, rare in Indian plant foods.",
    healthTip: "Rohu, Katla and Hilsa are richest in omega-3. 2 servings of fish per week meets recommended omega-3 needs.",
    glycemicIndex: 0,
    badge: "Omega-3 Rich"
  },
  {
    id: "mutton",
    name: "Mutton (Goat Curry)",
    emoji: "🍖",
    category: "nonveg",
    serving: "1 serving (150g)",
    calories: 295,
    protein: 27.0,
    carbs: 2.5,
    fat: 19.0,
    fiber: 0.5,
    sugar: 0.5,
    vitamins: { B12: 2.5, B3: 6.5, B6: 0.45, B2: 0.3, Zinc: 5.3 },
    minerals: { Iron: 3.6, Phosphorus: 285, Zinc: 5.3, Selenium: 12, Potassium: 360 },
    tags: ["non-veg", "high-protein", "iron-rich", "zinc-rich"],
    description: "Goat curry — red meat rich in zinc and haem iron, far more bioavailable than plant sources.",
    healthTip: "Lean cuts (leg, shoulder) are best. Limit to 2-3 times a week. The spice base makes it anti-inflammatory.",
    glycemicIndex: 0,
    badge: "Zinc Rich"
  }
];

const TIPS = [
  {
    icon: "🥗",
    title: "The Perfect Thali Formula",
    body: "A balanced thali should have: ½ plate vegetables, ¼ plate dal/protein, ¼ plate complex grains (roti/brown rice), plus a small bowl of dahi. This naturally hits all macro and micro nutrient targets.",
    tag: "Meal Design"
  },
  {
    icon: "⏰",
    title: "Meal Timing Matters",
    body: "Eat your largest meal at lunch (12–2 PM) when digestive fire (agni) is strongest. Keep dinner before 8 PM and light. This aligns with India's traditional food wisdom and modern circadian nutrition research.",
    tag: "Timing"
  },
  {
    icon: "🌿",
    title: "Power of Spices",
    body: "Indian spices are functional foods: haldi (anti-inflammatory), jeera (digestive), methi (blood sugar), ajwain (bloating), hing (gut health). Use whole spices in tadka to release maximum essential oils.",
    tag: "Spices"
  },
  {
    icon: "🫘",
    title: "Vegetarian Protein Strategy",
    body: "Combine incomplete plant proteins: dal + roti, rice + curd, or peanut chutney + idli. Each pair creates a complementary amino acid profile equivalent to animal protein.",
    tag: "Protein"
  },
  {
    icon: "💧",
    title: "Hydration: Indian Way",
    body: "Don't drink water during meals — it dilutes digestive enzymes. Instead sip warm water 30 min before meals. Chaas (buttermilk) and coconut water are ideal post-meal hydrators.",
    tag: "Hydration"
  },
  {
    icon: "🩺",
    title: "Managing Diabetes Indianly",
    body: "Replace white rice with jowar/bajra rotis. Add fenugreek seeds to atta. Eat dal before rice to slow glucose absorption. Include karela and bitter foods regularly.",
    tag: "Diabetes"
  }
];

const NUTRIENT_COLORS = {
  protein: "#e74c3c",
  carbs: "#f39c12",
  fat: "#9b59b6",
  fiber: "#27ae60",
  sugar: "#e67e22"
};
